### ISSUE TITLE
cannot shuffle new deck

### ISSUE THREAD

**Issue by kenany** [mohebifar/pasoor#2]
Test case (Node.js v6.3.1):

``` js
const Deck = require('pasoor').Deck;

const deck = new Deck();
deck.shuffleAll();
```

```
/home/kenan/code/beep/node_modules/pasoor/lib/Deck.js:208
      this.held.empty();
                ^

TypeError: this.held.empty is not a function
    at Deck.shuffleAll (/home/kenan/code/beep/node_modules/pasoor/lib/Deck.js:208:17)
    at Object.<anonymous> (/home/kenan/code/beep/index.js:5:6)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)
```

**Comment by kenany** [comment]
@mohebifar ping :)

**Comment by mohebifar** [comment]
I just made this repo in a few hours for some reason but never used it. I don't know if I can maintain it anymore. If you would like to continue working on it, I can transfer it for you.

**Comment by kenany** [comment]
@mohebifar Feel free to add me as a collaborator on GitHub and npm.

**Comment by mohebifar** [comment]
Done!

**Comment by kenany** [comment]
@mohebifar Thanks! I'm gonna reopen this since it's still a bug and I haven't yet found the fix yet.

**Comment by kenany** [comment]
Babel removed the ability to extend natives like `Array`, see https://phabricator.babeljs.io/T1424. Will need to workaround this, working on it now.

**Comment by mohebifar** [comment]
Wow! You've done so much! Thanks for your effort.
